DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    id BIGINT PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    ssn VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL
);